import { useState, useEffect } from 'react';
import type { Timeline, TimelineNovella, NovellaGenerateRequest, NovellaContinueRequest } from '../types';
import {
  getTimelineNovellas,
  generateNovella,
  continueNovella,
  deleteNovella,
} from '../services/api';
import { BookOpen, Plus, Trash2, ChevronRight, Download } from 'lucide-react';

function downloadNovellaMarkdown(novella: TimelineNovella): void {
  const lines: string[] = [];

  if (novella.series_id) {
    lines.push(`*Part ${novella.series_order}*`, '');
  }

  lines.push(`# ${novella.title}`, '', '---', '', novella.content, '', '---', '');
  lines.push(`*Generated by ${novella.model_provider}/${novella.model_name}*`);

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');

  const safeTitle = novella.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 60);
  const filename = novella.series_id
    ? `part_${novella.series_order}_${safeTitle}.md`
    : `${safeTitle}.md`;

  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

interface NovellaPanelProps {
  timeline: Timeline;
}

type PanelMode = 'read' | 'write-new' | 'write-continue';

export default function NovellaPanel({ timeline }: NovellaPanelProps) {
  const [novellas, setNovellas] = useState<TimelineNovella[]>([]);
  const [selected, setSelected] = useState<TimelineNovella | null>(null);
  const [mode, setMode] = useState<PanelMode>('write-new');
  const [continueSource, setContinueSource] = useState<TimelineNovella | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Form state
  const [selectedGenIds, setSelectedGenIds] = useState<string[]>([]);
  const [focusInstructions, setFocusInstructions] = useState('');

  useEffect(() => { fetchNovellas(); }, [timeline.id]);

  const fetchNovellas = async () => {
    const res = await getTimelineNovellas(timeline.id);
    if (res.data) setNovellas(res.data);
  };

  const handleGenerate = async () => {
    if (selectedGenIds.length === 0) return;
    setIsLoading(true);
    setError(null);
    try {
      const req: NovellaGenerateRequest = {
        generation_ids: selectedGenIds,
        focus_instructions: focusInstructions || undefined,
      };
      const res = mode === 'write-continue' && continueSource
        ? await continueNovella(continueSource.id, req as NovellaContinueRequest)
        : await generateNovella(timeline.id, req);

      if (res.error) { setError(res.error.message); return; }
      await fetchNovellas();
      if (res.data) { setSelected(res.data); setMode('read'); }
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async (novella: TimelineNovella) => {
    if (!confirm(`Delete "${novella.title}"?`)) return;
    await deleteNovella(novella.id);
    await fetchNovellas();
    if (selected?.id === novella.id) { setSelected(null); setMode('write-new'); }
  };

  const handleContinue = (novella: TimelineNovella) => {
    setContinueSource(novella);
    setMode('write-continue');
    setSelectedGenIds([]);
    setFocusInstructions('');
  };

  // Group novellas: series grouped together, standalones flat
  const seriesMap = new Map<string, TimelineNovella[]>();
  const standalones: TimelineNovella[] = [];
  for (const n of novellas) {
    if (n.series_id) {
      const arr = seriesMap.get(n.series_id) ?? [];
      arr.push(n);
      seriesMap.set(n.series_id, arr);
    } else {
      standalones.push(n);
    }
  }

  const isLastInSeries = (n: TimelineNovella): boolean => {
    if (!n.series_id) return true;
    const members = seriesMap.get(n.series_id) ?? [];
    return n.series_order === Math.max(...members.map(m => m.series_order));
  };

  const generations = timeline.generations ?? [];

  return (
    <div className="flex h-full min-h-0">
      {/* ── Sidebar ── */}
      <aside className="w-72 shrink-0 border-r border-border flex flex-col bg-surface">
        <div className="p-4 border-b border-border">
          <button
            onClick={() => { setMode('write-new'); setSelected(null); setContinueSource(null); setSelectedGenIds([]); setFocusInstructions(''); }}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm font-body text-gold border border-gold/40 hover:bg-gold/5 transition-colors"
          >
            <Plus size={14} /> Write New Novella
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-3 space-y-2">
          {/* Series groups — enclosed card */}
          {Array.from(seriesMap.entries()).map(([sid, members]) => (
            <div key={sid} className="border border-gold/20 bg-vellum/30">
              <div className="px-3 py-1.5 border-b border-gold/20 bg-gold/5">
                <p className="rubric-label text-[10px]">
                  Series · {members.length} {members.length === 1 ? 'part' : 'parts'}
                </p>
              </div>
              <div>
                {members.sort((a, b) => a.series_order - b.series_order).map(n => (
                  <NovellaEntry
                    key={n.id}
                    novella={n}
                    isSelected={selected?.id === n.id}
                    showContinue={isLastInSeries(n)}
                    onSelect={() => { setSelected(n); setMode('read'); }}
                    onContinue={() => handleContinue(n)}
                    onDelete={() => handleDelete(n)}
                    onDownload={() => downloadNovellaMarkdown(n)}
                  />
                ))}
              </div>
            </div>
          ))}

          {/* Standalones — individual cards */}
          {standalones.map(n => (
            <div key={n.id} className="border border-border/50">
              <NovellaEntry
                novella={n}
                isSelected={selected?.id === n.id}
                showContinue
                onSelect={() => { setSelected(n); setMode('read'); }}
                onContinue={() => handleContinue(n)}
                onDelete={() => handleDelete(n)}
                onDownload={() => downloadNovellaMarkdown(n)}
              />
            </div>
          ))}

          {novellas.length === 0 && (
            <p className="text-dim text-xs font-body px-1 py-4 text-center">
              No novellas yet.<br />Write your first one.
            </p>
          )}
        </div>
      </aside>

      {/* ── Main area ── */}
      <main className="flex-1 overflow-y-auto">
        {mode === 'read' && selected ? (
          <NovellaReader novella={selected} />
        ) : (
          <NovellaGeneratorForm
            generations={generations}
            selectedGenIds={selectedGenIds}
            onGenIdsChange={setSelectedGenIds}
            focusInstructions={focusInstructions}
            onFocusChange={setFocusInstructions}
            onSubmit={handleGenerate}
            isLoading={isLoading}
            error={error}
            isContinuation={mode === 'write-continue'}
            continuationTitle={continueSource?.title}
            seriesOrder={continueSource
              ? (seriesMap.get(continueSource.series_id ?? '') ?? [continueSource]).length + 1
              : 1}
          />
        )}
      </main>
    </div>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────────

function NovellaEntry({
  novella, isSelected, showContinue, onSelect, onContinue, onDelete, onDownload,
}: {
  novella: TimelineNovella;
  isSelected: boolean;
  showContinue: boolean;
  onSelect: () => void;
  onContinue: () => void;
  onDelete: () => void;
  onDownload: () => void;
}) {
  return (
    <div className={`group px-2 py-2 cursor-pointer transition-colors ${isSelected ? 'bg-gold/10 border-l-2 border-gold' : 'hover:bg-surface/60 border-l-2 border-transparent'}`}>
      <div onClick={onSelect} className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          {novella.series_id && (
            <span className="rubric-label text-[10px] block mb-0.5">
              Part {novella.series_order}
            </span>
          )}
          <p className="font-body text-sm text-ink truncate">{novella.title}</p>
        </div>
        <div className="flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0 mt-0.5">
          <button
            onClick={(e) => { e.stopPropagation(); onDownload(); }}
            title="Export as Markdown"
            className="text-dim hover:text-gold transition-colors"
          >
            <Download size={12} />
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); onDelete(); }}
            title="Delete"
            className="text-dim hover:text-rubric transition-colors"
          >
            <Trash2 size={12} />
          </button>
        </div>
      </div>
      {showContinue && (
        <button
          onClick={(e) => { e.stopPropagation(); onContinue(); }}
          className="mt-1.5 flex items-center gap-1 text-[11px] text-gold/70 hover:text-gold transition-colors font-body"
        >
          <ChevronRight size={10} /> Continue Story
        </button>
      )}
    </div>
  );
}

function NovellaReader({ novella }: { novella: TimelineNovella }) {
  return (
    <article className="max-w-2xl mx-auto px-8 py-12">
      <div className="flex items-start justify-between gap-4 mb-8">
        <div>
          {novella.series_id && (
            <p className="rubric-label text-xs mb-3">Part {novella.series_order}</p>
          )}
          <h1 className="font-display text-3xl text-gold leading-tight">{novella.title}</h1>
        </div>
        <button
          onClick={() => downloadNovellaMarkdown(novella)}
          title="Export as Markdown"
          className="shrink-0 mt-1 text-dim hover:text-gold transition-colors"
        >
          <Download size={16} />
        </button>
      </div>
      <div className="font-body text-ink text-base leading-relaxed whitespace-pre-wrap">
        {novella.content}
      </div>
      <p className="mt-10 text-dim text-xs font-caption">
        Generated by {novella.model_provider}/{novella.model_name}
      </p>
    </article>
  );
}

function NovellaGeneratorForm({
  generations, selectedGenIds, onGenIdsChange, focusInstructions, onFocusChange,
  onSubmit, isLoading, error, isContinuation, continuationTitle, seriesOrder,
}: {
  generations: any[];
  selectedGenIds: string[];
  onGenIdsChange: (ids: string[]) => void;
  focusInstructions: string;
  onFocusChange: (v: string) => void;
  onSubmit: () => void;
  isLoading: boolean;
  error: string | null;
  isContinuation: boolean;
  continuationTitle?: string;
  seriesOrder: number;
}) {
  const toggle = (id: string) =>
    onGenIdsChange(
      selectedGenIds.includes(id)
        ? selectedGenIds.filter(x => x !== id)
        : [...selectedGenIds, id]
    );

  return (
    <div className="max-w-2xl mx-auto px-8 py-12 space-y-8">
      <div>
        <p className="rubric-label text-xs mb-1">
          {isContinuation ? `Part ${seriesOrder} — Continuation of "${continuationTitle}"` : '§ New Novella'}
        </p>
        <h2 className="font-display text-2xl text-gold">
          {isContinuation ? 'Continue the Story' : 'Write a Novella'}
        </h2>
      </div>

      <div className="space-y-3">
        <p className="font-body text-sm text-dim">Select source generations (in order):</p>
        {generations.length === 0 && (
          <p className="text-dim text-sm font-body">No generations available.</p>
        )}
        {generations.map((gen) => (
          <label key={gen.id} className="flex items-center gap-3 cursor-pointer group">
            <input
              type="checkbox"
              checked={selectedGenIds.includes(gen.id)}
              onChange={() => toggle(gen.id)}
              className="accent-gold"
            />
            <span className="font-body text-sm text-ink group-hover:text-gold transition-colors">
              {gen.start_year}–{gen.end_year}
              {gen.generation_type !== 'initial' && (
                <span className="ml-2 text-dim text-xs">{gen.generation_type}</span>
              )}
            </span>
          </label>
        ))}
      </div>

      <div className="space-y-2">
        <label className="rubric-label text-xs">Author's Brief (optional)</label>
        <textarea
          value={focusInstructions}
          onChange={(e) => onFocusChange(e.target.value)}
          placeholder="e.g. Follow a resistance leader through the occupation. Focus on the human cost rather than geopolitics."
          rows={4}
          className="w-full bg-parchment border border-border text-ink font-body text-sm px-3 py-2 resize-none focus:outline-none focus:border-gold/60 placeholder:text-dim/50"
        />
      </div>

      {error && (
        <p className="text-rubric text-sm font-body">{error}</p>
      )}

      <button
        onClick={onSubmit}
        disabled={isLoading || selectedGenIds.length === 0}
        className="px-6 py-2 bg-gold text-vellum font-body text-sm font-medium hover:bg-gold-2 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        {isLoading ? 'Writing\u2026' : isContinuation ? 'Generate Continuation' : 'Generate Novella'}
      </button>
      {isLoading && (
        <p className="text-dim text-xs font-body">
          The agent is writing your novella — this takes 60–120 seconds.
        </p>
      )}
    </div>
  );
}

// Re-export BookOpen so it's used (suppresses unused import warning)
export { BookOpen };
