import { motion } from 'motion/react';
import type { Generation, Timeline, SupportedLanguage, TranslationResponse } from '../types';
import { exportStructuredReport, exportStructuredReportEnhanced } from '../utils/exportUtils';
import TranslateButton from './TranslateButton';
import { LanguageSelector } from './LanguageSelector';
import { Download } from 'lucide-react';

interface StructuredReportViewProps {
  generation: Generation;
  timeline: Timeline;
  translatedContent?: {
    executive_summary: string;
    political_changes: string;
    conflicts_and_wars: string;
    economic_impacts: string;
    social_developments: string;
    technological_shifts: string;
    key_figures: string;
    long_term_implications: string;
  };
  currentLanguage?: SupportedLanguage;
  onTranslated?: () => void;
  onLanguageChange?: (lang: SupportedLanguage) => void;
  onTranslationComplete?: (data: TranslationResponse) => void;
}

const SECTIONS = [
  { id: 'executive-summary',      field: 'executive_summary',      label: 'Executive Summary'    },
  { id: 'political-changes',      field: 'political_changes',      label: 'Political Changes'    },
  { id: 'conflicts-wars',         field: 'conflicts_and_wars',     label: 'Conflicts & Wars'     },
  { id: 'economic-impacts',       field: 'economic_impacts',       label: 'Economic Impacts'     },
  { id: 'social-developments',    field: 'social_developments',    label: 'Social Developments'  },
  { id: 'technological-shifts',   field: 'technological_shifts',   label: 'Technological Shifts' },
  { id: 'key-figures',            field: 'key_figures',            label: 'Key Figures'          },
  { id: 'long-term-implications', field: 'long_term_implications', label: 'Long-term Implications'},
] as const;

const formatProvider = (p: string) =>
  p === 'google' ? 'Google' : p === 'openrouter' ? 'OpenRouter' : p;

const StructuredReportView = ({
  generation,
  timeline,
  translatedContent,
  currentLanguage = 'en',
  onTranslated,
  onLanguageChange,
}: StructuredReportViewProps) => {
  const content = translatedContent || generation;

  const handleExport = () => {
    try {
      if (translatedContent && currentLanguage !== 'en') {
        exportStructuredReportEnhanced(generation, timeline, translatedContent, currentLanguage);
      } else {
        exportStructuredReport(generation, timeline);
      }
    } catch {
      alert('Failed to export. Please try again.');
    }
  };

  return (
    <div className="space-y-0">

      {/* ── Controls bar ─────────────────────────────────────────── */}
      <div className="flex items-center justify-between pb-5 mb-6 border-b border-border">
        <div className="flex items-center gap-3">
          {onLanguageChange && (
            <LanguageSelector currentLanguage={currentLanguage} onLanguageChange={onLanguageChange} />
          )}
          {currentLanguage !== 'en' && (
            <TranslateButton
              generationId={generation.id}
              targetLanguage={currentLanguage}
              type="generation"
              onTranslated={() => onTranslated?.()}
              onDelete={() => onTranslated?.()}
            />
          )}
        </div>

        <button
          onClick={handleExport}
          className="flex items-center gap-2 font-mono text-[10px] tracking-widest uppercase text-dim hover:text-gold transition-colors duration-150 cursor-pointer"
        >
          <Download size={11} />
          Export as Markdown
        </button>
      </div>

      {/* ── Model provenance ──────────────────────────────────────── */}
      {generation.report_model_provider && generation.report_model_name && (
        <div className="flex items-center gap-2 mb-6 font-mono text-[10px] text-faint tracking-wide">
          <span>Generated by</span>
          <span className="text-quantum">{formatProvider(generation.report_model_provider)}</span>
          <span>·</span>
          <span>{generation.report_model_name}</span>
        </div>
      )}

      {/* ── Translation notice ────────────────────────────────────── */}
      {translatedContent && currentLanguage !== 'en' && (
        <div className="mb-6 border border-gold-dim px-4 py-2.5 font-mono text-[10px] text-dim tracking-widest uppercase">
          Viewing translation · {currentLanguage.toUpperCase()}
        </div>
      )}

      {/* ── Report sections ───────────────────────────────────────── */}
      {SECTIONS.map(({ id, field, label }, i) => (
        <motion.section
          key={id}
          id={id}
          className={`scroll-mt-20 py-7 ${i < SECTIONS.length - 1 ? 'border-b border-border' : ''}`}
          initial={{ opacity: 0, y: 14 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-40px' }}
          transition={{ duration: 0.38, ease: [0.4, 0, 0.2, 1], delay: i < 3 ? i * 0.05 : 0 }}
        >
          {/* Section title */}
          <div className="flex items-baseline gap-3 mb-4">
            <h3 className="font-display text-xl text-gold leading-tight">{label}</h3>
          </div>

          {/* Body text */}
          <p className="font-body text-[17px] text-ink leading-[1.75] whitespace-pre-wrap">
            {(content as any)[field]}
          </p>
        </motion.section>
      ))}
    </div>
  );
};

export default StructuredReportView;
