"""
Media service for redesigned schema.

This module provides CRUD operations for:
- Media (images, audio, video) attached to generations
- Image prompt skeletons (review-before-generate workflow)
"""

import logging
from typing import List, Optional
from uuid import UUID, uuid4
from datetime import datetime, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete
from sqlalchemy.orm import selectinload

from app.db_models import MediaDB, ImagePromptSkeletonDB, GenerationDB, TimelineDB
from app.models import ImagePromptSkeletonStatus

logger = logging.getLogger(__name__)


# ============================================================================
# Image Prompt Skeletons (Review-Before-Generate Workflow)
# ============================================================================


async def create_image_prompt_skeleton(
    db: AsyncSession,
    timeline_id: UUID,
    generation_id: Optional[UUID],
    num_images: int,
    focus_areas: Optional[List[str]],
    prompts: List[dict],
    model_provider: Optional[str] = None,
    model_name: Optional[str] = None,
) -> dict:
    """
    Create an image prompt skeleton from AI agent output.

    Args:
        db: Database session
        timeline_id: UUID of the timeline
        generation_id: Optional UUID of specific generation
        num_images: Number of images to generate
        focus_areas: Optional focus areas for image generation
        prompts: List of image prompts generated by illustrator agent
        model_provider: LLM provider used
        model_name: Specific model used

    Returns:
        dict: Created skeleton with prompts
    """
    skeleton_id = str(uuid4())

    # Get timeline to extract deviation date for year validation
    result = await db.execute(
        select(TimelineDB).where(TimelineDB.id == str(timeline_id))
    )
    db_timeline = result.scalar_one_or_none()

    if db_timeline:
        deviation_year = int(db_timeline.root_deviation_date.split("-")[0])

        # Validate and fix event_year values in prompts
        # Convert absolute years to relative years if LLM made a mistake
        for prompt in prompts:
            event_year = prompt.get("event_year")
            if event_year is not None and event_year > 100:
                # Looks like an absolute year, convert to relative
                relative_year = event_year - deviation_year
                logger.warning(
                    f"Converting absolute year {event_year} to relative year {relative_year} "
                    f"(deviation year: {deviation_year})"
                )
                prompt["event_year"] = relative_year

    # Create skeleton record
    db_skeleton = ImagePromptSkeletonDB(
        id=skeleton_id,
        timeline_id=str(timeline_id),
        generation_id=str(generation_id) if generation_id else None,
        status=ImagePromptSkeletonStatus.PENDING.value,
        num_images=num_images,
        focus_areas=focus_areas,
        prompts_json=prompts,
        model_provider=model_provider,
        model_name=model_name,
        created_at=datetime.now(timezone.utc),
    )

    db.add(db_skeleton)
    await db.flush()

    logger.info(
        f"Created image prompt skeleton {skeleton_id} with {len(prompts)} prompts "
        f"for timeline {timeline_id}, generation {generation_id}"
    )

    return await get_image_prompt_skeleton(db, UUID(skeleton_id))


async def get_image_prompt_skeleton(
    db: AsyncSession, skeleton_id: UUID
) -> Optional[dict]:
    """
    Get an image prompt skeleton by ID.

    Args:
        db: Database session
        skeleton_id: Skeleton UUID

    Returns:
        Optional[dict]: Skeleton if found, None otherwise
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if not skeleton:
        logger.warning(f"Image prompt skeleton not found: {skeleton_id}")
        return None

    return {
        "id": UUID(skeleton.id),
        "timeline_id": UUID(skeleton.timeline_id),
        "generation_id": UUID(skeleton.generation_id) if skeleton.generation_id else None,
        "status": skeleton.status,
        "num_images": skeleton.num_images,
        "focus_areas": skeleton.focus_areas,
        "prompts": skeleton.prompts_json,
        "model_provider": skeleton.model_provider,
        "model_name": skeleton.model_name,
        "created_at": skeleton.created_at,
        "approved_at": skeleton.approved_at,
        "completed_at": skeleton.completed_at,
        "updated_at": skeleton.updated_at,
    }


async def get_image_prompt_skeletons_by_timeline(
    db: AsyncSession, timeline_id: UUID
) -> List[dict]:
    """
    Get all image prompt skeletons for a timeline.

    Args:
        db: Database session
        timeline_id: Timeline UUID

    Returns:
        List[dict]: List of skeletons
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB)
        .where(ImagePromptSkeletonDB.timeline_id == str(timeline_id))
        .order_by(ImagePromptSkeletonDB.created_at.desc())
    )
    skeletons = result.scalars().all()

    responses = []
    for skeleton in skeletons:
        skeleton_data = await get_image_prompt_skeleton(db, UUID(skeleton.id))
        if skeleton_data:
            responses.append(skeleton_data)

    logger.info(f"Retrieved {len(responses)} image prompt skeletons for timeline {timeline_id}")
    return responses


async def get_image_prompt_skeletons_by_generation(
    db: AsyncSession, generation_id: UUID
) -> List[dict]:
    """
    Get all image prompt skeletons for a generation.

    Args:
        db: Database session
        generation_id: Generation UUID

    Returns:
        List[dict]: List of skeletons
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB)
        .where(ImagePromptSkeletonDB.generation_id == str(generation_id))
        .order_by(ImagePromptSkeletonDB.created_at.desc())
    )
    skeletons = result.scalars().all()

    responses = []
    for skeleton in skeletons:
        skeleton_data = await get_image_prompt_skeleton(db, UUID(skeleton.id))
        if skeleton_data:
            responses.append(skeleton_data)

    logger.info(f"Retrieved {len(responses)} image prompt skeletons for generation {generation_id}")
    return responses


async def update_image_prompts(
    db: AsyncSession,
    skeleton_id: UUID,
    prompts_update: List[dict],
    deleted_prompt_indices: List[int]
) -> dict:
    """
    Update prompts in an image prompt skeleton (modify, add, delete).

    Args:
        db: Database session
        skeleton_id: Skeleton UUID
        prompts_update: List of prompts to update or add (with prompt_order)
        deleted_prompt_indices: List of prompt_order indices to delete

    Returns:
        dict: Updated skeleton

    Raises:
        ValueError: If skeleton not found or already completed
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if not skeleton:
        raise ValueError(f"Image prompt skeleton not found: {skeleton_id}")

    if skeleton.status == ImagePromptSkeletonStatus.COMPLETED.value:
        raise ValueError("Cannot update skeleton after completion")

    # The frontend sends the COMPLETE list of prompts (not just changes)
    # So we replace the entire prompts_json with the new list
    # deleted_prompt_indices tells us which ones to explicitly exclude

    # Convert deleted indices to a set for fast lookup
    deleted_indices_set = set(deleted_prompt_indices)

    # Build the new prompts list
    updated_prompts = []
    for prompt_update in prompts_update:
        # Convert Pydantic model to dict
        if hasattr(prompt_update, 'model_dump'):
            prompt_dict = prompt_update.model_dump()
        elif hasattr(prompt_update, 'dict'):
            prompt_dict = prompt_update.dict()
        else:
            prompt_dict = prompt_update

        prompt_order = prompt_dict.get("prompt_order")

        # Only include if not in deleted list
        if prompt_order is not None and prompt_order not in deleted_indices_set:
            updated_prompts.append(prompt_dict)

    # Sort by prompt_order
    updated_prompts = sorted(updated_prompts, key=lambda p: p.get("prompt_order", 0))

    skeleton.prompts_json = updated_prompts
    skeleton.status = ImagePromptSkeletonStatus.EDITING.value
    skeleton.updated_at = datetime.now(timezone.utc)

    await db.flush()

    logger.info(
        f"Updated skeleton {skeleton_id}: {len(prompts_update)} prompts processed, "
        f"{len(deleted_prompt_indices)} deleted"
    )

    # Expire the skeleton object to force a fresh load from database
    # This ensures we get the latest prompts_json after updates
    db.expire(skeleton)

    return await get_image_prompt_skeleton(db, skeleton_id)


async def approve_image_prompt_skeleton(db: AsyncSession, skeleton_id: UUID) -> dict:
    """
    Approve an image prompt skeleton for generation.

    Args:
        db: Database session
        skeleton_id: Skeleton UUID

    Returns:
        dict: Approved skeleton

    Raises:
        ValueError: If skeleton not found
    """
    # CRITICAL: Expire all objects to prevent loading stale cached skeleton
    # This ensures we get the latest prompts_json from the database after any edits
    db.expire_all()

    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if not skeleton:
        raise ValueError(f"Image prompt skeleton not found: {skeleton_id}")

    skeleton.status = ImagePromptSkeletonStatus.APPROVED.value
    skeleton.approved_at = datetime.now(timezone.utc)
    skeleton.updated_at = datetime.now(timezone.utc)

    await db.flush()

    logger.info(f"Approved image prompt skeleton {skeleton_id}")

    # Reload from database to get fresh state
    return await get_image_prompt_skeleton(db, skeleton_id)


async def mark_skeleton_generating(db: AsyncSession, skeleton_id: UUID) -> dict:
    """
    Mark skeleton as generating.

    Args:
        db: Database session
        skeleton_id: Skeleton UUID

    Returns:
        dict: Updated skeleton
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if skeleton:
        skeleton.status = ImagePromptSkeletonStatus.GENERATING.value
        skeleton.updated_at = datetime.now(timezone.utc)
        await db.flush()

    return await get_image_prompt_skeleton(db, skeleton_id)


async def mark_skeleton_completed(db: AsyncSession, skeleton_id: UUID) -> dict:
    """
    Mark skeleton as completed.

    Args:
        db: Database session
        skeleton_id: Skeleton UUID

    Returns:
        dict: Updated skeleton
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if skeleton:
        skeleton.status = ImagePromptSkeletonStatus.COMPLETED.value
        skeleton.completed_at = datetime.now(timezone.utc)
        skeleton.updated_at = datetime.now(timezone.utc)
        await db.flush()

    return await get_image_prompt_skeleton(db, skeleton_id)


async def delete_image_prompt_skeleton(db: AsyncSession, skeleton_id: UUID) -> bool:
    """
    Delete an image prompt skeleton.

    Args:
        db: Database session
        skeleton_id: Skeleton UUID

    Returns:
        bool: True if deleted, False if not found
    """
    result = await db.execute(
        select(ImagePromptSkeletonDB).where(
            ImagePromptSkeletonDB.id == str(skeleton_id)
        )
    )
    skeleton = result.scalar_one_or_none()

    if not skeleton:
        logger.warning(f"Cannot delete - skeleton not found: {skeleton_id}")
        return False

    await db.delete(skeleton)
    await db.flush()

    logger.info(f"Deleted image prompt skeleton {skeleton_id}")
    return True


# ============================================================================
# Media (Images, Audio, Video)
# ============================================================================


async def create_media(
    db: AsyncSession,
    generation_id: UUID,
    media_type: str,
    media_url: str,
    media_order: int,
    prompt_text: Optional[str] = None,
    media_local_path: Optional[str] = None,
    event_year: Optional[int] = None,
    title: Optional[str] = None,
    description: Optional[str] = None,
    is_user_added: bool = False,
    model_provider: Optional[str] = None,
    model_name: Optional[str] = None,
) -> dict:
    """
    Create a media record (image, audio, or video).

    Args:
        db: Database session
        generation_id: Generation UUID
        media_type: Type of media (image, audio, video)
        media_url: URL to media file
        media_order: Display order within generation
        prompt_text: AI prompt used for generation
        media_local_path: Local file path (optional)
        event_year: Associated year in timeline
        title: User-friendly title
        description: Caption or description
        is_user_added: True if manually added by user
        model_provider: LLM provider that generated prompt
        model_name: Model that generated prompt

    Returns:
        dict: Created media record
    """
    media_id = str(uuid4())

    db_media = MediaDB(
        id=media_id,
        generation_id=str(generation_id),
        media_type=media_type,
        media_order=media_order,
        prompt_text=prompt_text,
        media_url=media_url,
        media_local_path=media_local_path,
        event_year=event_year,
        title=title,
        description=description,
        is_user_added=1 if is_user_added else 0,
        is_user_modified=0,
        model_provider=model_provider,
        model_name=model_name,
        created_at=datetime.now(timezone.utc),
    )

    db.add(db_media)
    await db.flush()

    logger.info(
        f"Created {media_type} media {media_id} for generation {generation_id} "
        f"(order: {media_order})"
    )

    return await get_media(db, UUID(media_id))


async def get_media(db: AsyncSession, media_id: UUID) -> Optional[dict]:
    """
    Get a media record by ID.

    Args:
        db: Database session
        media_id: Media UUID

    Returns:
        Optional[dict]: Media if found, None otherwise
    """
    from sqlalchemy.orm import selectinload

    result = await db.execute(
        select(MediaDB)
        .options(selectinload(MediaDB.generation))
        .where(MediaDB.id == str(media_id))
    )
    media = result.scalar_one_or_none()

    if not media:
        logger.warning(f"Media not found: {media_id}")
        return None

    # Get timeline_id from generation
    timeline_id = None
    if media.generation:
        timeline_id = UUID(media.generation.timeline_id)

    return {
        "id": UUID(media.id),
        "timeline_id": timeline_id,
        "generation_id": UUID(media.generation_id),
        "media_type": media.media_type,
        "media_order": media.media_order,
        "prompt_text": media.prompt_text,
        "media_url": media.media_url,
        "image_url": media.media_url,  # Alias for backward compatibility
        "media_local_path": media.media_local_path,
        "event_year": media.event_year,
        "title": media.title,
        "description": media.description,
        "is_user_added": bool(media.is_user_added),
        "is_user_modified": bool(media.is_user_modified),
        "model_provider": media.model_provider,
        "model_name": media.model_name,
        "created_at": media.created_at,
    }


async def get_media_by_generation(
    db: AsyncSession, generation_id: UUID, media_type: Optional[str] = None
) -> List[dict]:
    """
    Get all media for a generation, optionally filtered by type.

    Args:
        db: Database session
        generation_id: Generation UUID
        media_type: Optional media type filter (image, audio, video)

    Returns:
        List[dict]: List of media records ordered by media_order
    """
    query = select(MediaDB).where(MediaDB.generation_id == str(generation_id))

    if media_type:
        query = query.where(MediaDB.media_type == media_type)

    query = query.order_by(MediaDB.media_order)

    result = await db.execute(query)
    media_list = result.scalars().all()

    responses = []
    for media in media_list:
        media_data = await get_media(db, UUID(media.id))
        if media_data:
            responses.append(media_data)

    logger.info(
        f"Retrieved {len(responses)} media items for generation {generation_id}"
        + (f" (type: {media_type})" if media_type else "")
    )
    return responses


async def get_media_by_timeline(
    db: AsyncSession, timeline_id: UUID, media_type: Optional[str] = None
) -> List[dict]:
    """
    Get all media for a timeline across all generations.

    Args:
        db: Database session
        timeline_id: Timeline UUID
        media_type: Optional media type filter (image, audio, video)

    Returns:
        List[dict]: List of media records
    """
    # Get all generations for timeline
    gen_result = await db.execute(
        select(GenerationDB).where(GenerationDB.timeline_id == str(timeline_id))
    )
    generations = gen_result.scalars().all()

    all_media = []
    for generation in generations:
        media_list = await get_media_by_generation(
            db, UUID(generation.id), media_type
        )
        all_media.extend(media_list)

    logger.info(
        f"Retrieved {len(all_media)} media items for timeline {timeline_id}"
        + (f" (type: {media_type})" if media_type else "")
    )
    return all_media


async def delete_media(db: AsyncSession, media_id: UUID) -> bool:
    """
    Delete a media record.

    Args:
        db: Database session
        media_id: Media UUID

    Returns:
        bool: True if deleted, False if not found
    """
    result = await db.execute(select(MediaDB).where(MediaDB.id == str(media_id)))
    media = result.scalar_one_or_none()

    if not media:
        logger.warning(f"Cannot delete - media not found: {media_id}")
        return False

    media_type = media.media_type
    generation_id = media.generation_id

    await db.delete(media)
    await db.flush()

    logger.info(
        f"Deleted {media_type} media {media_id} from generation {generation_id}"
    )
    return True
