"""
Pytest configuration and fixtures for API endpoint tests.

Provides FastAPI TestClient and mock services for testing routers.
"""

import pytest
import pytest_asyncio
from fastapi.testclient import TestClient
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from typing import AsyncGenerator
from unittest.mock import AsyncMock, MagicMock, patch

from app.main import app
from app.database import get_db


# ============================================================================
# FastAPI TestClient Fixtures
# ============================================================================


@pytest.fixture
def override_get_db(db_session: AsyncSession):
    """Override get_db dependency to use test database."""
    async def _override_get_db():
        yield db_session
    return _override_get_db


@pytest.fixture
def test_client(override_get_db):
    """
    Create FastAPI TestClient with test database.

    Uses dependency override to inject test database session.
    """
    app.dependency_overrides[get_db] = override_get_db

    with TestClient(app) as client:
        yield client

    # Clean up dependency overrides
    app.dependency_overrides.clear()


@pytest_asyncio.fixture
async def async_test_client(override_get_db) -> AsyncGenerator[AsyncClient, None]:
    """
    Create async FastAPI test client for async operations.

    Useful for testing async endpoints with streaming responses.
    """
    app.dependency_overrides[get_db] = override_get_db

    async with AsyncClient(app=app, base_url="http://test") as client:
        yield client

    # Clean up dependency overrides
    app.dependency_overrides.clear()


# ============================================================================
# Mock Service Fixtures
# ============================================================================


@pytest.fixture
def mock_historian_agent():
    """Mock Historian Agent responses with predictable output."""
    with patch("app.agents.historian_agent.generate_report_from_deviation") as mock:
        mock.return_value = {
            "executive_summary": "Test executive summary from mock",
            "political_changes": "Test political changes from mock",
            "economic_impacts": "Test economic impacts from mock",
            "social_developments": "Test social developments from mock",
            "technological_shifts": "Test technological shifts from mock",
            "conflicts_and_wars": "Test conflicts from mock",
            "key_figures": "Test key figures from mock",
            "long_term_implications": "Test implications from mock",
        }
        yield mock


@pytest.fixture
def mock_storyteller_agent():
    """Mock Storyteller Agent responses with predictable narrative."""
    with patch("app.agents.storyteller_agent.generate_narrative") as mock:
        mock.return_value = "This is a test narrative generated by the mock storyteller agent."
        yield mock


@pytest.fixture
def mock_skeleton_agent():
    """Mock Skeleton Agent responses with predictable events."""
    with patch("app.agents.skeleton_agent.generate_skeleton_events") as mock:
        mock.return_value = [
            {
                "event_date": "1914-06-28",
                "event_year": 0,
                "location": "Sarajevo",
                "description": "Mock event 1",
                "event_order": 0,
            },
            {
                "event_date": "1914-08-01",
                "event_year": 0,
                "location": "Vienna",
                "description": "Mock event 2",
                "event_order": 1,
            },
        ]
        yield mock


@pytest.fixture
def mock_illustrator_agent():
    """Mock Illustrator Agent responses with predictable image prompts."""
    with patch("app.agents.illustrator_agent.generate_image_prompts") as mock:
        mock.return_value = [
            {
                "prompt_text": "Mock image prompt 1",
                "event_year": 0,
                "title": "Mock Image 1",
                "description": "Description for mock image 1",
            },
            {
                "prompt_text": "Mock image prompt 2",
                "event_year": 5,
                "title": "Mock Image 2",
                "description": "Description for mock image 2",
            },
        ]
        yield mock


@pytest.fixture
def mock_script_writer_agent():
    """Mock Script Writer Agent responses with predictable audio scripts."""
    with patch("app.agents.script_writer_agent.generate_script") as mock:
        mock.return_value = "This is a mock audio script generated for testing."
        yield mock


@pytest.fixture
def mock_translator_agent():
    """Mock Translator Agent responses with predictable translations."""
    with patch("app.agents.translator_agent.translate_content") as mock:
        mock.return_value = "Ez egy teszt fordítás a mock ügynöktől."
        yield mock


@pytest.fixture
def mock_deepl_service():
    """Mock DeepL API calls for translation tests."""
    with patch("app.services.deepl_service.translate_text") as mock:
        mock.return_value = "Mock DeepL translation"
        yield mock


@pytest.fixture
def mock_llm_service():
    """Mock LLM service for predictable API responses."""
    with patch("app.services.llm_service.get_completion") as mock:
        mock.return_value = "Mock LLM completion response"
        yield mock


@pytest.fixture
def mock_pollinations_api():
    """Mock Pollinations.ai image generation API."""
    with patch("app.services.media_service.generate_image_url") as mock:
        mock.return_value = "https://mock-pollinations.ai/image123.jpg"
        yield mock


@pytest.fixture
def mock_google_tts():
    """Mock Google TTS API for audio generation."""
    with patch("app.services.audio_service.generate_audio_file") as mock:
        mock.return_value = {
            "file_path": "/data/audio/mock_audio_123.mp3",
            "duration_seconds": 180,
        }
        yield mock


@pytest.fixture
def mock_orchestrator():
    """Mock Orchestrator for workflow testing."""
    with patch("app.agents.orchestrator.run_workflow") as mock:
        mock.return_value = {
            "status": "completed",
            "result": "Mock workflow result",
        }
        yield mock


# ============================================================================
# Helper Fixtures for Common Test Scenarios
# ============================================================================


@pytest.fixture
def sample_deviation_request():
    """Sample deviation request for timeline generation tests."""
    return {
        "deviation_date": "1914-06-28",
        "deviation_description": "Franz Ferdinand survives the assassination attempt",
        "simulation_years": 10,
        "scenario_type": "local_deviation",
        "narrative_mode": "basic",
    }


@pytest.fixture
def sample_skeleton_request():
    """Sample skeleton generation request."""
    return {
        "deviation_date": "1914-06-28",
        "deviation_description": "Franz Ferdinand survives the assassination attempt",
        "simulation_years": 10,
        "scenario_type": "local_deviation",
    }


@pytest.fixture
def sample_extension_request(timeline_db):
    """Sample timeline extension request."""
    return {
        "timeline_id": timeline_db.id,
        "additional_years": 10,
        "context": "Focus on economic development",
        "narrative_mode": "basic",
    }


@pytest.fixture
def sample_image_generation_request(timeline_db):
    """Sample image generation request."""
    return {
        "timeline_id": timeline_db.id,
        "num_images": 5,
        "focus_areas": ["political", "economic"],
    }


@pytest.fixture
def sample_audio_script_request(timeline_db):
    """Sample audio script generation request."""
    return {
        "generation_ids": [timeline_db.generations[0].id],
        "preset_id": "preset-documentary",
        "custom_instructions": "Focus on key events",
    }


# ============================================================================
# Utility Fixtures
# ============================================================================


@pytest.fixture
def assert_response_model():
    """Helper function to assert response matches Pydantic model."""
    def _assert_response_model(response_data: dict, model_class):
        """Validate response data against Pydantic model."""
        try:
            model_instance = model_class(**response_data)
            return model_instance
        except Exception as e:
            pytest.fail(f"Response does not match {model_class.__name__}: {e}")

    return _assert_response_model


@pytest.fixture
def assert_db_count():
    """Helper function to assert database record count."""
    async def _assert_db_count(db_session: AsyncSession, model_class, expected_count: int):
        """Count records of given model in database."""
        from sqlalchemy import select, func
        result = await db_session.execute(select(func.count()).select_from(model_class))
        actual_count = result.scalar()
        assert actual_count == expected_count, (
            f"Expected {expected_count} {model_class.__name__} records, "
            f"found {actual_count}"
        )

    return _assert_db_count
