/**
 * Export Utilities for Markdown file generation
 *
 * Provides functions to export timeline generations as formatted Markdown files.
 * Supports separate exports for structured reports and narrative prose.
 * Enhanced with translation support for bilingual exports.
 */

import type { Timeline, Generation, SupportedLanguage } from '../types';

/**
 * Sanitize a string for use in filenames.
 * Removes special characters and limits length.
 */
export function sanitizeFilename(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')  // Replace non-alphanumeric with underscore
    .replace(/^_+|_+$/g, '')      // Remove leading/trailing underscores
    .substring(0, 50);             // Limit length to 50 characters
}

/**
 * Generate a descriptive filename for export.
 *
 * Format: {deviation}__{generation-label}__{years}__{type}.md
 * Example: stock_market_crash_prevention__original__1929-1949__structured.md
 */
export function generateFilename(
  timeline: Timeline,
  generation: Generation,
  type: 'structured' | 'narrative' | `structured_${string}` | `narrative_${string}`
): string {
  const deviationSlug = sanitizeFilename(timeline.root_deviation_description);

  const generationLabel = generation.generation_order === 1
    ? 'original'
    : `extension_${generation.generation_order - 1}`;

  const deviationYear = new Date(timeline.root_deviation_date).getFullYear();
  const startYear = deviationYear + generation.start_year;
  const endYear = deviationYear + generation.end_year;

  return `${deviationSlug}__${generationLabel}__${startYear}-${endYear}__${type}.md`;
}

/**
 * Get generation label for display.
 */
function getGenerationLabel(generation: Generation): string {
  return generation.generation_order === 1
    ? 'Original Timeline'
    : `Extension ${generation.generation_order - 1}`;
}

/**
 * Get absolute years for display.
 */
function getAbsoluteYears(timeline: Timeline, generation: Generation): string {
  const deviationYear = new Date(timeline.root_deviation_date).getFullYear();
  const startYear = deviationYear + generation.start_year;
  const endYear = deviationYear + generation.end_year;
  return `${startYear}-${endYear}`;
}

/**
 * Format provider name for display.
 */
function formatProviderName(provider: string): string {
  const providerMap: Record<string, string> = {
    'google': 'Google Gemini',
    'openrouter': 'OpenRouter',
    'ollama': 'Ollama',
  };
  return providerMap[provider] || provider;
}

/**
 * Generate Markdown content for a structured report.
 */
export function generateStructuredReportMarkdown(
  generation: Generation,
  timeline: Timeline
): string {
  const generationLabel = getGenerationLabel(generation);
  const absoluteYears = getAbsoluteYears(timeline, generation);
  const currentDate = new Date().toLocaleString();

  // Build metadata section
  const metadata: string[] = [
    `# ${timeline.root_deviation_description} - Structured Report`,
    '',
    `**Generation**: ${generationLabel}`,
    `**Time Period**: Years ${generation.start_year}-${generation.end_year} (${generation.period_years} ${generation.period_years === 1 ? 'year' : 'years'})`,
    `**Absolute Years**: ${absoluteYears}`,
    `**Generated**: ${new Date(generation.created_at).toLocaleDateString()}`,
  ];

  // Add model info if available
  if (generation.report_model_provider && generation.report_model_name) {
    metadata.push(`**Model**: ${formatProviderName(generation.report_model_provider)} - ${generation.report_model_name}`);
  }

  metadata.push('', '---', '');

  // Build sections
  const sections: string[] = [
    '## Executive Summary',
    '',
    generation.executive_summary,
    '',
    '---',
    '',
    '## Political Changes',
    '',
    generation.political_changes,
    '',
    '---',
    '',
    '## Conflicts and Wars',
    '',
    generation.conflicts_and_wars,
    '',
    '---',
    '',
    '## Economic Impacts',
    '',
    generation.economic_impacts,
    '',
    '---',
    '',
    '## Social Developments',
    '',
    generation.social_developments,
    '',
    '---',
    '',
    '## Technological Shifts',
    '',
    generation.technological_shifts,
    '',
    '---',
    '',
    '## Key Figures',
    '',
    generation.key_figures,
    '',
    '---',
    '',
    '## Long-term Implications',
    '',
    generation.long_term_implications,
    '',
  ];

  // Build footer
  const footer: string[] = [
    '---',
    '',
    '*Generated by Deviation Engine*',
    `*Exported on: ${currentDate}*`,
  ];

  return [...metadata, ...sections, ...footer].join('\n');
}

/**
 * Generate Markdown content for a structured report with optional translation support.
 * Enhanced version that can include translated content when available.
 */
export function generateStructuredReportMarkdownEnhanced(
  generation: Generation,
  timeline: Timeline,
  translatedContent?: {
    executive_summary: string;
    political_changes: string;
    conflicts_and_wars: string;
    economic_impacts: string;
    social_developments: string;
    technological_shifts: string;
    key_figures: string;
    long_term_implications: string;
  },
  currentLanguage?: SupportedLanguage
): string {
  const generationLabel = getGenerationLabel(generation);
  const absoluteYears = getAbsoluteYears(timeline, generation);
  const currentDate = new Date().toLocaleString();

  // Determine if we should use translation
  const useTranslation = translatedContent && currentLanguage && currentLanguage !== 'en';
  const content = useTranslation ? translatedContent : generation;

  // Build metadata section
  const metadata: string[] = [
    `# ${timeline.root_deviation_description} - Structured Report`,
    '',
    `**Generation**: ${generationLabel}`,
    `**Time Period**: Years ${generation.start_year}-${generation.end_year} (${generation.period_years} ${generation.period_years === 1 ? 'year' : 'years'})`,
    `**Absolute Years**: ${absoluteYears}`,
    `**Generated**: ${new Date(generation.created_at).toLocaleDateString()}`,
  ];

  // Add model info if available
  if (generation.report_model_provider && generation.report_model_name) {
    metadata.push(`**Model**: ${formatProviderName(generation.report_model_provider)} - ${generation.report_model_name}`);
  }

  // Add translation info if using translation
  if (useTranslation) {
    metadata.push(`**Translation**: Translated from English to ${currentLanguage.toUpperCase()}`);
    metadata.push(`**Translated on**: ${currentDate}`);
  }

  metadata.push('', '---', '');

  // Build sections
  const sections: string[] = [
    '## Executive Summary',
    '',
    content.executive_summary,
    '',
    '---',
    '',
    '## Political Changes',
    '',
    content.political_changes,
    '',
    '---',
    '',
    '## Conflicts and Wars',
    '',
    content.conflicts_and_wars,
    '',
    '---',
    '',
    '## Economic Impacts',
    '',
    content.economic_impacts,
    '',
    '---',
    '',
    '## Social Developments',
    '',
    content.social_developments,
    '',
    '---',
    '',
    '## Technological Shifts',
    '',
    content.technological_shifts,
    '',
    '---',
    '',
    '## Key Figures',
    '',
    content.key_figures,
    '',
    '---',
    '',
    '## Long-term Implications',
    '',
    content.long_term_implications,
    '',
  ];

  // Build footer
  const footer: string[] = [
    '---',
    '',
    '*Generated by Deviation Engine*',
    `*Exported on: ${currentDate}*`,
  ];

  return [...metadata, ...sections, ...footer].join('\n');
}

/**
 * Generate Markdown content for narrative prose with optional translation support.
 * Enhanced version that can include translated narrative when available.
 */
export function generateNarrativeMarkdownEnhanced(
  generation: Generation,
  timeline: Timeline,
  translatedNarrative?: string,
  currentLanguage?: SupportedLanguage
): string {
  if (!generation.narrative_prose && !translatedNarrative) {
    throw new Error('This generation does not have narrative prose');
  }

  const generationLabel = getGenerationLabel(generation);
  const absoluteYears = getAbsoluteYears(timeline, generation);
  const currentDate = new Date().toLocaleString();

  // Determine if we should use translation
  const useTranslation = translatedNarrative && currentLanguage && currentLanguage !== 'en';
  const narrativeText = useTranslation ? translatedNarrative : generation.narrative_prose!;

  // Build metadata section
  const metadata: string[] = [
    `# ${timeline.root_deviation_description} - Narrative`,
    '',
    `**Generation**: ${generationLabel}`,
    `**Time Period**: Years ${generation.start_year}-${generation.end_year} (${generation.period_years} ${generation.period_years === 1 ? 'year' : 'years'})`,
    `**Absolute Years**: ${absoluteYears}`,
    `**Generated**: ${new Date(generation.created_at).toLocaleDateString()}`,
  ];

  // Add narrative model info if available
  if (generation.narrative_model_provider && generation.narrative_model_name) {
    metadata.push(`**Narrative Model**: ${formatProviderName(generation.narrative_model_provider)} - ${generation.narrative_model_name}`);
  }

  // Add translation info if using translation
  if (useTranslation) {
    metadata.push(`**Translation**: Translated from English to ${currentLanguage.toUpperCase()}`);
    metadata.push(`**Translated on**: ${currentDate}`);
  }

  metadata.push('', '---', '');

  // Add narrative content
  const content: string[] = [
    narrativeText,
    '',
  ];

  // Build footer
  const footer: string[] = [
    '---',
    '',
    '*Generated by Deviation Engine*',
    `*Exported on: ${currentDate}*`,
  ];

  return [...metadata, ...content, ...footer].join('\n');
}

/**
 * Generate Markdown content for narrative prose.
 */
export function generateNarrativeMarkdown(
  generation: Generation,
  timeline: Timeline
): string {
  if (!generation.narrative_prose) {
    throw new Error('This generation does not have narrative prose');
  }

  const generationLabel = getGenerationLabel(generation);
  const absoluteYears = getAbsoluteYears(timeline, generation);
  const currentDate = new Date().toLocaleString();

  // Build metadata section
  const metadata: string[] = [
    `# ${timeline.root_deviation_description} - Narrative`,
    '',
    `**Generation**: ${generationLabel}`,
    `**Time Period**: Years ${generation.start_year}-${generation.end_year} (${generation.period_years} ${generation.period_years === 1 ? 'year' : 'years'})`,
    `**Absolute Years**: ${absoluteYears}`,
    `**Generated**: ${new Date(generation.created_at).toLocaleDateString()}`,
  ];

  // Add narrative model info if available
  if (generation.narrative_model_provider && generation.narrative_model_name) {
    metadata.push(`**Narrative Model**: ${formatProviderName(generation.narrative_model_provider)} - ${generation.narrative_model_name}`);
  }

  metadata.push('', '---', '');

  // Add narrative content
  const content: string[] = [
    generation.narrative_prose,
    '',
  ];

  // Build footer
  const footer: string[] = [
    '---',
    '',
    '*Generated by Deviation Engine*',
    `*Exported on: ${currentDate}*`,
  ];

  return [...metadata, ...content, ...footer].join('\n');
}

/**
 * Download markdown content as a file.
 * Uses the browser's download API to save the file locally.
 */
export function downloadMarkdownFile(content: string, filename: string): void {
  try {
    // Create blob with UTF-8 encoding
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });

    // Create temporary download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';

    // Trigger download
    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Failed to download file:', error);
    throw new Error('Failed to download markdown file. Please try again.');
  }
}

/**
 * Export structured report as markdown file.
 * Combines generation and download in one function.
 */
export function exportStructuredReport(
  generation: Generation,
  timeline: Timeline
): void {
  const markdown = generateStructuredReportMarkdown(generation, timeline);
  const filename = generateFilename(timeline, generation, 'structured');
  downloadMarkdownFile(markdown, filename);
}

/**
 * Export narrative as markdown file.
 * Combines generation and download in one function.
 */
export function exportNarrative(
  generation: Generation,
  timeline: Timeline
): void {
  if (!generation.narrative_prose) {
    throw new Error('This generation does not have narrative prose');
  }

  const markdown = generateNarrativeMarkdown(generation, timeline);
  const filename = generateFilename(timeline, generation, 'narrative');
  downloadMarkdownFile(markdown, filename);
}

/**
 * Export structured report as markdown file with translation support.
 * Enhanced version that can include translated content when available.
 */
export function exportStructuredReportEnhanced(
  generation: Generation,
  timeline: Timeline,
  translatedContent?: {
    executive_summary: string;
    political_changes: string;
    conflicts_and_wars: string;
    economic_impacts: string;
    social_developments: string;
    technological_shifts: string;
    key_figures: string;
    long_term_implications: string;
  },
  currentLanguage?: SupportedLanguage
): void {
  const markdown = generateStructuredReportMarkdownEnhanced(
    generation,
    timeline,
    translatedContent,
    currentLanguage
  );
  
  // Add language suffix to filename if using translation
  let type: 'structured' | `structured_${string}` = 'structured';
  if (translatedContent && currentLanguage && currentLanguage !== 'en') {
    type = `structured_${currentLanguage}`;
  }
  
  const filename = generateFilename(timeline, generation, type);
  downloadMarkdownFile(markdown, filename);
}

/**
 * Export narrative as markdown file with translation support.
 * Enhanced version that can include translated narrative when available.
 */
export function exportNarrativeEnhanced(
  generation: Generation,
  timeline: Timeline,
  translatedNarrative?: string,
  currentLanguage?: SupportedLanguage
): void {
  if (!generation.narrative_prose && !translatedNarrative) {
    throw new Error('This generation does not have narrative prose');
  }

  const markdown = generateNarrativeMarkdownEnhanced(
    generation,
    timeline,
    translatedNarrative,
    currentLanguage
  );
  
  // Add language suffix to filename if using translation
  let type: 'narrative' | `narrative_${string}` = 'narrative';
  if (translatedNarrative && currentLanguage && currentLanguage !== 'en') {
    type = `narrative_${currentLanguage}`;
  }
  
  const filename = generateFilename(timeline, generation, type);
  downloadMarkdownFile(markdown, filename);
}
